### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by jewbmx** [teamuniversal/scrapers#8]
Getting bored and starting to update your scraper pile on my end. Would yall like me to fork and pull my work? Otherwise it will just be a zip in my repo with a letter at the end of the version lol

**Comment by Greenhousecafe** [comment]
Can you send a pull request and someone will take a look?

**Comment by jewbmx** [comment]
K figured id ask first. I'll finish up today and get the PR going sometime tonight.

Theres 2 that arent used but are already fixed i can add in as well, swatch with a little limit code added to reduce results. And think the other is putlocker from the temp folder that now has a new working domain. Cfscrape will also be updated most likely.
